GoalApp/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :show, :create, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :goals
    get"/goals/:id/complete", to: "goals#complete"
  get '/', to: 'sessions#new'
end

GoalApp/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  details    :text
#  visibility :string           not null
#  finished   :string           default("ongoing"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          default(-1), not null
#

class Goal < ActiveRecord::Base
  validates :title, :visibility, :finished, :user_id, presence: true

  belongs_to :user


end

GoalApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :password_digest, :session_token, presence:true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :goals

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    if user.valid_password?(password)
      return user
    else
      nil
    end
  end

  def valid_password?(password)
    pass = BCrypt::Password.new(self.password_digest)
    pass.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end
end

GoalApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def log_out
    current_user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end
end

GoalApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      render :show
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find_by_id(params[:id])
    if @goal.user_id != current_user.id
      render :show
    end
    render :edit
  end

  def update
    @goal = Goal.find_by_id(params[:id])
    if @goal.update_attributes(goal_params)
      render :show
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find_by_id(params[:id])
    if @goal.user_id != current_user.id
      render :show
    end

    @goal.destroy
    redirect_to user_url(current_user)
  end

  def show
    @goal = Goal.find_by_id(params[:id])
  end

  def complete
    @goal = Goal.find_by_id(params[:id])
    @goal.finished = (@goal.finished == "true" ? "false" : "true")
    @goal.save
    render :show
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :details, :finished, :visibility)
  end
end

GoalApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_credentials(session_params[:username], session_params[:password])
    if user.nil?
      flash[:errors] = "Username or Password not found"
      redirect_to new_session_url
    else
      log_in!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

  private

  def session_params
    params.require(:user).permit(:username, :password)
  end
end

GoalApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

GoalApp/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\"".html_safe
  end
end

GoalApp/app/helpers/goals_helper.rb
module GoalsHelper
end

GoalApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

GoalApp/app/helpers/users_helper.rb
module UsersHelper
end

GoalApp/app/views/goals/_goals.html.erb
<ul>
<% goals.each do |goal|%>

<li><%= link_to goal.title, goal_url(goal)%>
<br>
<%= @goal.visibility == 'true' ? 'Public' : 'Private' %>
<br>
<%= @goal.finished == 'true' ? 'finished' : 'Ongoing' %>
<br>
<% if current_user == goal.user %>
<%= button_to "Complete", method: :get %>
<%= button_to "Delete", goal_url(goal), method: :delete  %>
<% end  %>
</li>
<% end %>
</ul>

GoalApp/app/views/goals/edit.html.erb
<h1>Edit goal</h1>

<form action="/goals" method="post">
  <%= auth_token %>
  <label for="Title">Title
    <input id="Title" type="text" name="goal[title]" value="<%= @goal.title %>">
  </label>
  <br>
  <label for="Details">Details
  <textarea id="Details" name="goal[details]" rows="8" cols="40"><%= @goal.details %></textarea>
  </label>
  <br>
  <label>Public?
  <input type="checkbox" name="goal[visibility]" value="true" <%= 'checked' if @goal.visibility == 'true' %>>
  </label>
  <br>
  <label>Completed?
  <input type="checkbox" name="goal[finished]" value="true" <%= 'checked' if @goal.finished == 'true' %>>
  </label>
  <br>

  <input type="submit" value="Edit goal">
</form>

GoalApp/app/views/goals/new.html.erb
<h1>New goal</h1>

<form action="/goals" method="post">
  <%= auth_token %>
  <label for="Title">Title
    <input type="text" name="goal[title]" id="Title">
  </label>
  <br>
  <label for="Details">Details</label>
  <textarea id="Details" name="goal[details]" rows="8" cols="40"></textarea>
  <br>
  <label>Public?
  <input type="checkbox" name="goal[visibility]" value="true">
  </label>
  <br>
  <label>Completed?
  <input type="checkbox" name="goal[finished]" value="true">
  </label>
  <br>

  <input type="submit" value="Create goal">

</form>

GoalApp/app/views/goals/show.html.erb
<h1>Goal</h1>

Title: <%= @goal.title %> <br>
Details: <%= @goal.details %> <br>
Visibility: <%= @goal.visibility == 'true' ? 'Public' : 'Private' %>
Completed? <%= @goal.finished == 'true' ? 'Completed' : 'Ongoing' %>

<%= link_to "Back to user", user_url(@goal.user_id) %>
<%= button_to "Edit goal", edit_goal_url(@goal) if current_user == @goal.user%>

GoalApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <% if current_user %>
    <%= button_to 'Log out', session_url, method: :delete %>
  <% end %>
</head>
<body>

<%= yield %>

</body>
</html>

GoalApp/app/views/users/index.html.erb
<ul>
<% User.all.each do |user| %>
<li> <%= link_to user.username, user_url(user) %> </li>
<% end %>
</ul>

GoalApp/app/views/users/new.html.erb
<h1>Sign up</h1>
<form action="<%= users_url %>" method="post">
    <%= auth_token %>
    <label for "Username">
      Username
      <input type="text" name="user[username]" id = "Username">
    </label>
    <br>
    <label>
      Password
      <input type="text" name="user[password]">
    </label>
    <br>
    <input type="submit" value="Sign up" >
</form>

GoalApp/app/views/users/show.html.erb
<%= current_user.username %>'s Profile Page
<br>
<%= link_to 'All Users', users_url %>